# -*- coding: utf-8 -*-
"""Copy of corizo_majors

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iecyCH5yjKTxOJPcRZly0K9Rq51XA_SG
"""

#Import necessary libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score
import numpy as np

#Load the dataset
df=pd.read_csv('/content/spotify dataset.csv')

# Fill missing values
df['track_name'].fillna('Unknown',inplace=True)
df['track_artist'].fillna('Unknown',inplace=True)
df['track_album_name'].fillna('Unknown',inplace=True)

df['track_album_release_date']=pd.to_datetime(df['track_album_release_date'],errors='coerce')

audio_features=['danceability','energy','key','loudness','mode','speechiness','acousticness','instrumentalness','liveness',
                'valence','tempo','duration_ms']

X=df[audio_features]
scaler=StandardScaler()
X_scaled=scaler.fit_transform(X)

plt.figure(figsize=(18,12))
for i,col in enumerate(audio_features):
 plt.subplot(3,4,i+1)
 sns.histplot(df[col],kde=True)
 plt.title(f'Distribution of {col}')
plt.tight_layout()
plt.show()

plt.figure(figsize=(12,8))
corr=df[audio_features].corr()
sns.heatmap(corr,annot=True,cmap='coolwarm')
plt.title('Correlation Matrix of Audio Features')
plt.show()

pca=PCA(n_components=2)
X_pca=pca.fit_transform(X_scaled)

# Determine optimal k using Elbow method
inertia=[]
K_range=range(2,11)
for k in K_range:
 km=KMeans(n_clusters=k,random_state=42)
 km.fit(X_scaled)
 inertia.append(km.inertia_)

plt.figure(figsize=(8,5))
plt.plot(K_range,inertia,'bo-')
plt.xlabel('Number of clusters (k)')
plt.ylabel('Inertia')
plt.title('Elbow Method for Optimal k')
plt.show()

kmeans=KMeans(n_clusters=5,random_state=42)
df['cluster']=kmeans.fit_predict(X_scaled)

score=silhouette_score(X_scaled,df['cluster'])
print("Silhouette Score:",score)

plt.figure(figsize=(10,7))
sns.scatterplot(x=X_pca[:,0],y=X_pca[:,1],hue=df['cluster'],palette='Set2')
plt.title('Clusters of Spotify Songs (PCA Reduced)')
plt.show()

cluster_summary=df.groupby('cluster')[audio_features].mean()
print("\nCluster-wise Feature Means:")
print(cluster_summary)

if 'playlist_genre' in df.columns:
 plt.figure(figsize=(12,6))
 sns.countplot(x='playlist_genre',hue='cluster',data=df)
 plt.title('Distribution of Playlist Genres Across Clusters')
 plt.xticks(rotation=45)
 plt.show()

def recommend_songs(track_name,n=5):
 song_data=df[df['track_name'].str.contains(track_name,case=False)]
 if song_data.empty:
  return f"No song found with name '{track_name}'"
 song_features=song_data.iloc[0][audio_features]
 song_scaled=scaler.transform([song_features])
 cluster_label=kmeans.predict(song_scaled)[0]
 cluster_songs=df[df['cluster']==cluster_label].copy()
 cluster_scaled=X_scaled[df['cluster']==cluster_label]
 distances=np.linalg.norm(cluster_scaled-song_scaled,axis=1)
 cluster_songs['distance']=distances
 recommendations=cluster_songs.nsmallest(n,'distance')[['track_name','track_artist','playlist_name']]
 return recommendations
print("\nRecommended Songs for 'Memories':")
print(recommend_songs('Memories'))